"""
0005_drop_dead_columns — drop legacy columns that no longer carry meaning.

  sentences.is_cached:
      Originally marked "this sentence was pre-generated by the CMS,
      not runtime-cached". Post read-layer refactor (commit f26265d) every
      sentence is pre-baked, so the column is always true. Keep the
      semantic meaning alive by removing the column — the API can stop
      pretending the runtime has a cache.

  sentences.is_stale:
      Originally intended for a "refresh stale sentences" cronjob that
      never landed. No code reads it; keeping it suggests functionality
      that doesn't exist.

  sentences.refresh_count:
      Same as is_stale — paired with it, never written, never read.

Subtractive, low risk. The backend / frontend code that referenced these
columns has been updated to no longer expect them.
"""
from __future__ import annotations

version = "0005_drop_dead_columns"
description = "Drop dead columns: sentences.is_cached, is_stale, refresh_count"

import psycopg2


def upgrade(conn) -> None:
    with conn.cursor() as cur:
        # DROP COLUMN IF EXISTS so re-runs are idempotent.
        cur.execute("ALTER TABLE sentences DROP COLUMN IF EXISTS refresh_count")
        cur.execute("ALTER TABLE sentences DROP COLUMN IF EXISTS is_stale")
        cur.execute("ALTER TABLE sentences DROP COLUMN IF EXISTS is_cached")


def downgrade(conn) -> None:
    with conn.cursor() as cur:
        # Re-add the columns with the same definitions they had before.
        # Existing rows get NULL (the columns were never written to anyway).
        cur.execute(
            "ALTER TABLE sentences ADD COLUMN IF NOT EXISTS is_cached BOOLEAN DEFAULT TRUE"
        )
        cur.execute(
            "ALTER TABLE sentences ADD COLUMN IF NOT EXISTS is_stale BOOLEAN DEFAULT FALSE"
        )
        cur.execute(
            "ALTER TABLE sentences ADD COLUMN IF NOT EXISTS refresh_count INTEGER DEFAULT 0"
        )